#version: "3.9"

services:
  app:
    build: .
    container_name: mi-app-node
    working_dir: /home/app
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - .:/home/app
      - ./img:/usr/src/app/public/img
      - /home/app/node_modules  #agregado
    env_file:
      - .env
    environment:
      NODE_ENV: production

    #command: node app.js

  ngrok:
    image: ngrok/ngrok:latest
    container_name: mi-ngrok
    depends_on:
    - app
    ports:
    - "4040:4040"
    restart: unless-stopped
    env_file:
    - .env
    command: http app:4000
    profiles: ["ngrok"]

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: mi-cloudflared
    depends_on:
      - app
    command: tunnel --no-autoupdate run #skill_JM #--url http://app:4000
    volumes:
    - ${PWD}/cloudflared:/etc/cloudflared  #./cloudflared:/etc/cloudflared
    profiles: ["cloudflare"]

    #docker-compose --profile ngrok up

    #docker-compose --profile cloudflare up