#version: "3.9"

services:
  app:
    build: .
    container_name: mi-app-node
    working_dir: /home/app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - ./img:/usr/src/app/public/img
      - /home/app/node_modules  #agregado
    environment:
      NODE_ENV: production
      DB_HOST: mysql-skilljm.alwaysdata.net
      DB_USER: skilljm
      DB_PASSWORD: Skill_JM1976#$
      DB_NAME: skilljm_04
      DB_PORT: 3306
    #command: node app.js
      