#version: "3.9"

services:
  app:
    build: .
    container_name: mi-app-node
    working_dir: /home/app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - ./img:/usr/src/app/public/img
      - /home/app/node_modules  #agregado
    env_file:
      - .env
    environment:
      NODE_ENV: production

    #command: node app.js

  ngrok:
    image: ngrok/ngrok:latest
    container_name: mi-ngrok
    depends_on:
    - app
    ports:
    - "4040:4040"
    env_file:
    - .env
    command: http app:4000
